apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita-test-deployment
spec:
  selector:
    matchLabels:
      app: sejutacita-test
  replicas: 2
  template:
    metadata:
      labels:
        app: sejutacita-test
    spec:
      containers:
        - name: sejutacita-test
          image: aoohan/sejutacita-test
          ports:
            - containerPort: 8000
          imagePullPolicy: Never