apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: sejutacita-test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000